version: '3.1'
services:
  ssm:                                        # 服务的名称
    build:                                      # 构建自定义镜像
      context: ../                              # 指定dockerfile文件的所在路径
      dockerfile: Dockerfile                    # 指定Dockerfile文件名称
    image: ssm:1.0.1
    container_name: ssm
    ports:
      - 8081:8080
    environment:
      TZ: Azsia/Shanghai